[package]
name = "tui_project_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19"
crossterm = "0.27.0" # terminal back-end
arboard = "3.2.1"
# rusqlite = "0.29.0"